// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nssdlzixurwqrkeyjvrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zc2Rseml4dXJ3cXJrZXlqdnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDI1OTQsImV4cCI6MjA1NzQ3ODU5NH0.OqS7-0MbVdeXRbEDcowGuXM-myRYAIXMaeSnsS0mD9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);